version: '3.3'
services:
    mi-template:
        image: "docker.io/wso2/wso2mi:4.1.0-multiarch"
        #image: "docker.wso2.com/wso2mi:latest"
        ports:
            - "8280:8280"
            - "8243:8243"
            - "9191:9191"
            - "9154:9154"
        volumes:
            - ./target/capp:/home/wso2carbon/wso2mi-4.1.0/repository/deployment/server/carbonapps
            - ./mi-home/conf/deployment.toml:/home/wso2carbon/wso2mi-4.1.0/conf/deployment.toml
