version: '3'
services:
<<<<<<< HEAD
    mi-demo:
=======
    mi-test-rabbitmq:
        container_name: 'mi-test-rabbitmq'
>>>>>>> a2f831f167dca6fa48120321af29343c9e0c9bc3
        image: "wso2/wso2mi:4.0.0"
        ports:
            - "8280:8080"
            - "8080:8080"
            - "8043:8043"
        volumes:
<<<<<<< HEAD
            - ./target/capp:/home/wso2carbon/wso2mi-4.0.0/repository/deployment/server/carbonapps
            - ./mi-home/conf/deployment.toml:/home/wso2carbon/wso2mi-4.0.0/conf/deployment.toml
=======
            - ./target/capp:/home/wso2carbon/wso2mi-1.2.0/repository/deployment/server/carbonapps
            - ./mi-home/conf/deployment.toml:/home/wso2carbon/wso2mi-1.2.0/conf/deployment.toml
>>>>>>> a2f831f167dca6fa48120321af29343c9e0c9bc3
