[server]
hostname = "localhost"
offset = 0

[transport.http]
listener.port = 8080
listener.secured_port = 8043

[management_api_basic_security_handler]
enable = true

[message_builders]
text_html = "org.apache.axis2.format.PlainTextBuilder"

[transport.rabbitmq]
sender_enable = true
listener_enable = true

[[transport.rabbitmq.sender]]
name = "AMQPConnectionFactory"
parameter.hostname = "localhost"
parameter.port = 5672
parameter.username = "guest"
parameter.password = "guest"

[[transport.rabbitmq.listener]]
name = "AMQPConnectionFactory"
parameter.hostname = "localhost"
parameter.port = 5672
parameter.username = "guest"
parameter.password = "guest"